### ISSUE TITLE
function error

### ISSUE THREAD

**Issue by gaurav150294** [stevenblair/simulink_sfcl#1]
"fcn" is givving an error in matlab R2010b 

how to resolve that error? i am not able to fix it

**Comment by stevenblair** [comment]
How are you using the code? The included .m file is just for reference only. All code is embedded within the SFCL.mdl library file, which should be used from Simulink.

Alternatively, if you are only interested in using the SFCL characteristic from within MATLAB, you could alter the .m file to be a valid MATLAB function: replace `fcn` with `sfcl_resistance_characteristic`.

**Comment by gaurav150294** [comment]
Sir,
I am still having issues in running sfcl on matlab
I am not able to get the mdl file from github
If possible could u please mail me that file at gaurav150294@gmail.com
Yours thankfully
Gaurav

**Comment by stevenblair** [comment]
The .mdl file can be downloaded from: https://raw.githubusercontent.com/stevenblair/simulink_sfcl/master/SFCL.mdl

Make sure that you then save this as a .mdl file on your computer.
