### ISSUE TITLE
Sfcl.mdl file

### ISSUE THREAD

**Issue by gaurav150294** [stevenblair/simulink_sfcl#2]
Respected sir/ma'am
I made the the whole system but still having issues with it 
If possible could you mail me SFCL.mdl file as m nt able to download through gethub. i need it for troubleshooting purpose 
Yours thankfully  
Gaurav 
Email id : gaurav150294@gmail.com

**Comment by stevenblair** [comment]
See the [other issue](https://github.com/stevenblair/simulink_sfcl/issues/1) for the response.
